- name: Playbook configure networkinterface
  hosts: all
  remote_user: root
  tasks:
  - name: stop NetworkManager
    service:
      name: NetworkManager
      state: stopped
      enabled: no
  - name: change configure GRUB
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE'
      line: 'GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop"'
  - name: run grub2-mkconfig
    shell: grub2-mkconfig /etc/default/grub
