- name: Playbook configure networkinterface
  hosts: all
  remote_user: root
  tasks:
  - name: stop NetworkManager
    service:
      name: NetworkManager
      state: stopped
    notify: 
     - start NetworkManager
  - name: change configure GRUB
    ansible.builtin.lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE'
      line: 'GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop"' 
  - name: run grub2-mkconfig
    ansible.builtin.shell: grub2-mkconfig /etc/default/grub
  handlers:
    - name: start NetworkManager
      service: 
        name: NetworkManager
        state: started
